LPS-66819 zookeeper requires package org.ietf.jgss to be imported
Otherwise it'll still generate

10:59:06,745 WARN  [liferay/search_writer/SYSTEM_ENGINE-2-SendThread(localhost:9983)][ClientCnxn:1162] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.lang.NoClassDefFoundError: org/ietf/jgss/GSSException
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1002)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
Caused by: java.lang.ClassNotFoundException: org.ietf.jgss.GSSException cannot be found by com.liferay.portal.search.solr_2.0.3
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:444)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:357)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:349)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)